// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUquKUA-JNeVZp9f3hhIsTERitywLp2fE',
    appId: '1:194841362814:web:167237bf615e4f37cc732f',
    messagingSenderId: '194841362814',
    projectId: 'smart-pgto',
    authDomain: 'smart-pgto.firebaseapp.com',
    storageBucket: 'smart-pgto.appspot.com',
    measurementId: 'G-FF3SCW0N1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKvgWfeCMdd53EV8cMIbmM7hYAWCjo-ho',
    appId: '1:194841362814:android:1e1ef2f91e43a05bcc732f',
    messagingSenderId: '194841362814',
    projectId: 'smart-pgto',
    storageBucket: 'smart-pgto.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUquKUA-JNeVZp9f3hhIsTERitywLp2fE',
    appId: '1:194841362814:web:e8e915931159f251cc732f',
    messagingSenderId: '194841362814',
    projectId: 'smart-pgto',
    authDomain: 'smart-pgto.firebaseapp.com',
    storageBucket: 'smart-pgto.appspot.com',
    measurementId: 'G-F01PYPP8V7',
  );
}
